### This configuration file is used to store teh login and store credentials for the system
# Each store could have its own entry so we seperate them in here

server localhost
port 5432
username store
password 
database postgres
roles dbrole
roles_password 
roles_chain roles
epos_user
epos_password
server_whitelist localhost
reward_point 1
stripe_secret_key <KEY>
